Add test using Kafka
It verifies if the trace from the current context matches the one from
`TracingMetadata`, after setting the current context from it. This
fails, which is not expected.

The test failure is reported like this:
```
org.opentest4j.AssertionFailedError: 2 elements passed but expected 3

The following elements passed:
  [0] (ProcessedItem(item=a1, traceIds=[(d0e4ec5339ea4d64782ad7a668058761, d0e4ec5339ea4d64782ad7a668058761), (d0e4ec5339ea4d64782ad7a668058761, d0e4ec5339ea4d64782ad7a668058761), (d0e4ec5339ea4d64782ad7a668058761, d0e4ec5339ea4d64782ad7a668058761)]), d0e4ec5339ea4d64782ad7a668058761)
  [1] (ProcessedItem(item=b1, traceIds=[(bab84c26343b6cb8755b5bb9aededa87, bab84c26343b6cb8755b5bb9aededa87), (bab84c26343b6cb8755b5bb9aededa87, bab84c26343b6cb8755b5bb9aededa87), (bab84c26343b6cb8755b5bb9aededa87, bab84c26343b6cb8755b5bb9aededa87)]), bab84c26343b6cb8755b5bb9aededa87)

The following elements failed:
  [2] (ProcessedItem(item=b2, traceIds=[(f2603eaebec04e8c993435a643de1d2c, f2603eaebec04e8c993435a643de1d2c), (f2603eaebec04e8c993435a643de1d2c, 00000000000000000000000000000000), (f2603eaebec04e8c993435a643de1d2c, f2603eaebec04e8c993435a643de1d2c)]), f2603eaebec04e8c993435a643de1d2c) => 2 elements passed but expected 3

The following elements passed:
  [0] (f2603eaebec04e8c993435a643de1d2c, f2603eaebec04e8c993435a643de1d2c)
  [2] (f2603eaebec04e8c993435a643de1d2c, f2603eaebec04e8c993435a643de1d2c)

The following elements failed:
  [1] (f2603eaebec04e8c993435a643de1d2c, 00000000000000000000000000000000) => expected:<f2603eaebec04e8c993435a643de1d2c> but was:<00000000000000000000000000000000>
```